"""Publish tested skills as Firestore records and downloadable packages."""

import json
import os
import zipfile
from pathlib import Path
from uuid import uuid4

import yaml
from google.cloud import firestore

from app.models import PublishedSkill, ReplayReport, SkillSpec

PROJECT = os.environ.get("GOOGLE_CLOUD_PROJECT", "ticket2skill-agentic-26")
ARTIFACT_ROOT = Path(os.environ.get("TICKET2SKILL_ARTIFACT_ROOT", "artifacts"))


def _agent_source(skill: SkillSpec) -> str:
    return f'''"""Generated Ticket2Skill agent: {skill.name} {skill.version}."""

SKILL_NAME = {skill.name!r}
SKILL_VERSION = {skill.version!r}
ALLOWED_TOOLS = {skill.allowed_tools!r}


def describe() -> dict[str, object]:
    return {{
        "name": SKILL_NAME,
        "version": SKILL_VERSION,
        "allowed_tools": ALLOWED_TOOLS,
    }}
'''


def publish_skill(skill: SkillSpec, report: ReplayReport) -> PublishedSkill:
    """Persist an evidence-backed registry entry and ZIP artifact."""

    if report.verdict != "PASS" or report.score != 100:
        raise ValueError("only a 100% held-out replay result can be published")
    registry_id = f"{skill.name}-{skill.version}-{uuid4().hex[:8]}"
    package_dir = ARTIFACT_ROOT / registry_id
    package_dir.mkdir(parents=True, exist_ok=False)

    skill_document = skill.model_dump(mode="json")
    (package_dir / "skill.yaml").write_text(
        yaml.safe_dump(skill_document, sort_keys=False), encoding="utf-8"
    )
    (package_dir / "policy.json").write_text(
        json.dumps([rule.model_dump() for rule in skill.policy_rules], indent=2),
        encoding="utf-8",
    )
    (package_dir / "eval-report.json").write_text(
        report.model_dump_json(indent=2), encoding="utf-8"
    )
    (package_dir / "agent.py").write_text(_agent_source(skill), encoding="utf-8")
    (package_dir / "README.md").write_text(
        f"# {skill.name} {skill.version}\n\n"
        f"Replay score: **{report.score}%** ({report.passed}/{report.total}).\n\n"
        "Generated by Ticket2Skill from synthetic resolved ticket evidence.\n",
        encoding="utf-8",
    )

    zip_path = ARTIFACT_ROOT / f"{registry_id}.zip"
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for file_path in sorted(package_dir.iterdir()):
            archive.write(file_path, arcname=f"{skill.name}-{skill.version}/{file_path.name}")

    firestore_path = f"agent_skills/{registry_id}"
    firestore.Client(project=PROJECT).document(firestore_path).set(
        {
            "registry_id": registry_id,
            "skill": skill_document,
            "replay_report": report.model_dump(mode="json"),
            "model": os.environ.get("TICKET2SKILL_MODEL", "gemini-3.5-flash"),
            "artifact": zip_path.name,
            "status": "PUBLISHED",
            "created_at": firestore.SERVER_TIMESTAMP,
        }
    )
    return PublishedSkill(
        registry_id=registry_id,
        name=skill.name,
        version=skill.version,
        replay_score=report.score,
        firestore_path=firestore_path,
        artifact_url=f"/api/artifacts/{registry_id}",
    )


def artifact_path(registry_id: str) -> Path:
    path = (ARTIFACT_ROOT / f"{registry_id}.zip").resolve()
    root = ARTIFACT_ROOT.resolve()
    if root not in path.parents or not path.is_file():
        raise FileNotFoundError(registry_id)
    return path
